source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target '心愿很忙' do
pod 'MMDrawerController'
pod 'SVProgressHUD'
pod 'Masonry'
pod 'BmobSDK'
pod 'YYText'
pod 'SDWebImage'
pod 'TZImagePickerController'
pod 'HUPhotoBrowser'
end
