source 'https://github.com/CocoaPods/Specs.git'
source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
platform :ios, '8.0'

target '心愿很忙' do

pod 'SVProgressHUD'
pod 'Masonry'
pod 'BmobSDK'
pod 'YYText'
pod 'SDWebImage'
pod 'TZImagePickerController'
pod 'HUPhotoBrowser'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'AlibcTradeSDK'
pod 'SVPullToRefresh'
pod 'MMDrawerController'
pod 'UITableView+FDTemplateLayoutCell'
pod ‘SRActionSheet’
pod 'STPopup'

end
