source 'https://github.com/CocoaPods/Specs.git'
source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
platform :ios, '8.0'

target '心愿很忙' do

pod 'SVProgressHUD'
pod 'Masonry'
pod 'SDWebImage'
pod 'TZImagePickerController'
pod 'HUPhotoBrowser'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'MMDrawerController'
pod 'STPopup'
pod 'MMDrawerController'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/UI’
pod 'REFrostedViewController'
pod 'YUSegment'
pod 'WMPageController'
pod 'SCAvatarBrowser'
pod 'ZYCornerRadius'
pod 'BmobSDK'
pod 'YYText'
pod 'RongCloudIM/IMLib', '~> 2.8.3'
pod 'RongCloudIM/IMKit', '~> 2.8.3'
pod 'RTRootNavigationController'
pod 'JCAlertController'
pod 'AXWireButton'

end
